<?php


namespace app\models;
use yii\db\ActiveRecord;

class TestForm extends ActiveRecord
{

    public static function tableName()
    {
        return 'posts';
    }
//    public $name;
//    public $email;
//    public $text;

    public function attributeLabels()
    {
        //return parent::attributeLabels(); // TODO: Change the autogenerated stub
        return [
            'name' => 'Full name',
            'email' => 'e-mail post',
            'text' => 'text message',
        ];

    }
    public function rules()
    {
        return [
            [['name', 'email'], 'required'],
            ['email', 'email'],
            ['text', 'trim'],

        ];
    }
}